# Generated by Django 4.0.4 on 2023-02-16 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(max_length=300)),
                ('meal_type', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snack', 'Snack')], max_length=20)),
                ('protein_amount', models.DecimalField(decimal_places=1, max_digits=5)),
                ('fat_amount', models.DecimalField(decimal_places=1, max_digits=5)),
                ('carbs_amount', models.DecimalField(decimal_places=1, max_digits=5)),
                ('calories', models.IntegerField()),
            ],
        ),
    ]
