# Generated by Django 4.1.6 on 2023-02-07 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0002_meal_meal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='meal_type',
            field=models.CharField(choices=[('B', 'Breakfast'), ('L', 'Lunch'), ('D', 'Dinner'), ('S', 'Snack')], max_length=1),
        ),
    ]
