# Generated by Django 4.0.4 on 2023-02-09 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0004_alter_meal_meal_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='meal_type',
            new_name='type',
        ),
    ]
