# Generated by Django 4.1.6 on 2023-02-11 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0005_rename_meal_type_meal_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='type',
            new_name='meal_type',
        ),
    ]
